language: erlang

env:
  global:
    - PLATFORM=linux
    - LUAROCKS_VER=2.2.0beta1
  matrix:
    - LUA=lua5.1 LUA_SFX=
    - LUA=lua5.2 LUA_SFX=
    - LUA=luajit LUA_SFX=jit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh
  - sudo pip install cpp-coveralls
  - sudo luarocks install luacov-coveralls --server=http://rocks.moonscript.org/dev

script: 
  - $LUA_SFX dummy_test.lua

after_success:
  - coveralls -b .. -r .. --dump c.report.json
  - luacov-coveralls -j c.report.json

notifications:
  email:
    on_success: change
    on_failure: always
