language: erlang

env:
  matrix:
    - LUA=lua5.1 LUA_INCDIR=/usr/include/lua5.1
    - LUA=lua5.2 LUA_INCDIR=/usr/include/lua5.2
    - LUA=luajit-2.0.0-beta9 LUA_INCDIR=/usr/include/luajit-2.0

branches:
  only:
    - master

before_install:
  - sudo apt-get install lua5.1
  - sudo apt-get install lua5.2
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo pip install cpp-coveralls
  - sudo luarocks install luacov-coveralls --server=http://rocks.moonscript.org/dev

script: 
  - $LUA dummy_test.lua

after_success:
  - coveralls -b .. -r .. --dump c.report.json
  - luacov-coveralls -j c.report.json
  - curl -v --form "json_file=@luacov.report.json;type=application/json" https://coveralls.io/api/v1/jobs

notifications:
  email:
    on_success: change
    on_failure: always
